# Description: Docker compose file for creating a MongoDB replica set with 1 node for local development
services:
  mongo1:
    hostname: mongo1
    image: mongo:8.0
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    command: mongod --replSet rs0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"

volumes:
  mongo1_data:
  mongo1_config:
